from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from app.services.vip.detection import detect_ai_content

router = APIRouter()

class DetectionRequest(BaseModel):
    text: str

class DetectionResponse(BaseModel):
    ai_generated_probability: float
    human_generated_probability: float
    assessment: str
    confidence: float

@router.post("/detection", response_model=DetectionResponse)
async def ai_content_detection(request: DetectionRequest):
    """
    Detect whether content was generated by AI.
    """
    try:
        result = await detect_ai_content(text=request.text)
        return result
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e)) 